# Generated by Django 3.2.2 on 2022-09-21 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groc_item', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_pprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ['groc_item'],
            },
        ),
    ]
